// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzdwzuxwdtpgyrfrwjcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6ZHd6dXh3ZHRwZ3lyZnJ3amN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTg0MjIsImV4cCI6MjA2NzEzNDQyMn0.b0ql18rj-0PmTuiDZbCwtTFMe0Y0KkqwXoezFACWSYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);